### ISSUE TITLE
Event start date 

### ISSUE THREAD

**Issue by boryto** [Olog/olog-service#25]
The logbook web client was updated with the functionality to support tracing of event start date. This change is not reflected in the olog-service.
This causes the errors when creating or editing logbook entries. 

https://github.com/Olog/logbook/commit/3fb5ca89c3ce8f2fd8232404b09ba26a8a6b80b5

How should we deal with this discrepancy?
We temporary fixed the web client by removing the field.

**Comment by berryma4** [comment]
I cleaned up the naming/branches on olog-service

branches 0.1.x are without the event time:
https://github.com/Olog/logbook/tree/0.1.x
https://github.com/Olog/olog-service/tree/0.1.x

master on on both are with the event time:
https://github.com/Olog/olog-service/tree/master
https://github.com/Olog/logbook/tree/master

I should note, that we are working on a new service that will be here:
(The main goal is to clean up the project to the rules of a Twelve Factor App, to be able to run multiple instances in a container orchestration environment)
https://github.com/Olog/olog-reactive-service

If you are interested, we can include you with the discussions.

**Comment by boryto** [comment]
Ok, TNX, It would be nice to know where the service is going.
